require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MergePluginsStatisticsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MergePluginsStatistic. As you add validations to MergePluginsStatistic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MergePluginsStatisticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all merge_plugins_statistics as @merge_plugins_statistics" do
      merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:merge_plugins_statistics)).to eq([merge_plugins_statistic])
    end
  end

  describe "GET #show" do
    it "assigns the requested merge_plugins_statistic as @merge_plugins_statistic" do
      merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
      get :show, {:id => merge_plugins_statistic.to_param}, valid_session
      expect(assigns(:merge_plugins_statistic)).to eq(merge_plugins_statistic)
    end
  end

  describe "GET #new" do
    it "assigns a new merge_plugins_statistic as @merge_plugins_statistic" do
      get :new, {}, valid_session
      expect(assigns(:merge_plugins_statistic)).to be_a_new(MergePluginsStatistic)
    end
  end

  describe "GET #edit" do
    it "assigns the requested merge_plugins_statistic as @merge_plugins_statistic" do
      merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
      get :edit, {:id => merge_plugins_statistic.to_param}, valid_session
      expect(assigns(:merge_plugins_statistic)).to eq(merge_plugins_statistic)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MergePluginsStatistic" do
        expect {
          post :create, {:merge_plugins_statistic => valid_attributes}, valid_session
        }.to change(MergePluginsStatistic, :count).by(1)
      end

      it "assigns a newly created merge_plugins_statistic as @merge_plugins_statistic" do
        post :create, {:merge_plugins_statistic => valid_attributes}, valid_session
        expect(assigns(:merge_plugins_statistic)).to be_a(MergePluginsStatistic)
        expect(assigns(:merge_plugins_statistic)).to be_persisted
      end

      it "redirects to the created merge_plugins_statistic" do
        post :create, {:merge_plugins_statistic => valid_attributes}, valid_session
        expect(response).to redirect_to(MergePluginsStatistic.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved merge_plugins_statistic as @merge_plugins_statistic" do
        post :create, {:merge_plugins_statistic => invalid_attributes}, valid_session
        expect(assigns(:merge_plugins_statistic)).to be_a_new(MergePluginsStatistic)
      end

      it "re-renders the 'new' template" do
        post :create, {:merge_plugins_statistic => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested merge_plugins_statistic" do
        merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
        put :update, {:id => merge_plugins_statistic.to_param, :merge_plugins_statistic => new_attributes}, valid_session
        merge_plugins_statistic.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested merge_plugins_statistic as @merge_plugins_statistic" do
        merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
        put :update, {:id => merge_plugins_statistic.to_param, :merge_plugins_statistic => valid_attributes}, valid_session
        expect(assigns(:merge_plugins_statistic)).to eq(merge_plugins_statistic)
      end

      it "redirects to the merge_plugins_statistic" do
        merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
        put :update, {:id => merge_plugins_statistic.to_param, :merge_plugins_statistic => valid_attributes}, valid_session
        expect(response).to redirect_to(merge_plugins_statistic)
      end
    end

    context "with invalid params" do
      it "assigns the merge_plugins_statistic as @merge_plugins_statistic" do
        merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
        put :update, {:id => merge_plugins_statistic.to_param, :merge_plugins_statistic => invalid_attributes}, valid_session
        expect(assigns(:merge_plugins_statistic)).to eq(merge_plugins_statistic)
      end

      it "re-renders the 'edit' template" do
        merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
        put :update, {:id => merge_plugins_statistic.to_param, :merge_plugins_statistic => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested merge_plugins_statistic" do
      merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
      expect {
        delete :destroy, {:id => merge_plugins_statistic.to_param}, valid_session
      }.to change(MergePluginsStatistic, :count).by(-1)
    end

    it "redirects to the merge_plugins_statistics list" do
      merge_plugins_statistic = MergePluginsStatistic.create! valid_attributes
      delete :destroy, {:id => merge_plugins_statistic.to_param}, valid_session
      expect(response).to redirect_to(merge_plugins_statistics_url)
    end
  end

end
