require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SmashSettingsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SmashSetting. As you add validations to SmashSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmashSettingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all smash_settings as @smash_settings" do
      smash_setting = SmashSetting.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:smash_settings)).to eq([smash_setting])
    end
  end

  describe "GET #show" do
    it "assigns the requested smash_setting as @smash_setting" do
      smash_setting = SmashSetting.create! valid_attributes
      get :show, {:id => smash_setting.to_param}, valid_session
      expect(assigns(:smash_setting)).to eq(smash_setting)
    end
  end

  describe "GET #new" do
    it "assigns a new smash_setting as @smash_setting" do
      get :new, {}, valid_session
      expect(assigns(:smash_setting)).to be_a_new(SmashSetting)
    end
  end

  describe "GET #edit" do
    it "assigns the requested smash_setting as @smash_setting" do
      smash_setting = SmashSetting.create! valid_attributes
      get :edit, {:id => smash_setting.to_param}, valid_session
      expect(assigns(:smash_setting)).to eq(smash_setting)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SmashSetting" do
        expect {
          post :create, {:smash_setting => valid_attributes}, valid_session
        }.to change(SmashSetting, :count).by(1)
      end

      it "assigns a newly created smash_setting as @smash_setting" do
        post :create, {:smash_setting => valid_attributes}, valid_session
        expect(assigns(:smash_setting)).to be_a(SmashSetting)
        expect(assigns(:smash_setting)).to be_persisted
      end

      it "redirects to the created smash_setting" do
        post :create, {:smash_setting => valid_attributes}, valid_session
        expect(response).to redirect_to(SmashSetting.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved smash_setting as @smash_setting" do
        post :create, {:smash_setting => invalid_attributes}, valid_session
        expect(assigns(:smash_setting)).to be_a_new(SmashSetting)
      end

      it "re-renders the 'new' template" do
        post :create, {:smash_setting => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested smash_setting" do
        smash_setting = SmashSetting.create! valid_attributes
        put :update, {:id => smash_setting.to_param, :smash_setting => new_attributes}, valid_session
        smash_setting.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested smash_setting as @smash_setting" do
        smash_setting = SmashSetting.create! valid_attributes
        put :update, {:id => smash_setting.to_param, :smash_setting => valid_attributes}, valid_session
        expect(assigns(:smash_setting)).to eq(smash_setting)
      end

      it "redirects to the smash_setting" do
        smash_setting = SmashSetting.create! valid_attributes
        put :update, {:id => smash_setting.to_param, :smash_setting => valid_attributes}, valid_session
        expect(response).to redirect_to(smash_setting)
      end
    end

    context "with invalid params" do
      it "assigns the smash_setting as @smash_setting" do
        smash_setting = SmashSetting.create! valid_attributes
        put :update, {:id => smash_setting.to_param, :smash_setting => invalid_attributes}, valid_session
        expect(assigns(:smash_setting)).to eq(smash_setting)
      end

      it "re-renders the 'edit' template" do
        smash_setting = SmashSetting.create! valid_attributes
        put :update, {:id => smash_setting.to_param, :smash_setting => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested smash_setting" do
      smash_setting = SmashSetting.create! valid_attributes
      expect {
        delete :destroy, {:id => smash_setting.to_param}, valid_session
      }.to change(SmashSetting, :count).by(-1)
    end

    it "redirects to the smash_settings list" do
      smash_setting = SmashSetting.create! valid_attributes
      delete :destroy, {:id => smash_setting.to_param}, valid_session
      expect(response).to redirect_to(smash_settings_url)
    end
  end

end
